[package]
name = "bench_curve_ops"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rand_core = "0.6.4"
blsttc = "8.0.2"

[[bench]]
name = "benchmark"
harness = false